"""The `nnp data` subcommands.

This is one of the two places side effects belong. Everything here reads a
configuration, calls into the data layer and prints, and every failure the data layer
raises leaves as an exit code rather than as a traceback.
"""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Annotated, NoReturn

import typer

from nnphysics.core.config import RunConfig, load_run_config
from nnphysics.core.errors import NNPhysicsError
from nnphysics.data.build import build_dataset
from nnphysics.data.layout import MANIFEST_NAME, NORMALISATION_NAME, dataset_dir
from nnphysics.data.manifest import Manifest, Split, read_manifest
from nnphysics.data.normalisation import fit_normalisation, write_normalisation
from nnphysics.data.verify import verify_dataset

__all__ = ["app"]

app = typer.Typer(
    name="data",
    help="Generate, verify and describe trajectory datasets.",
    no_args_is_help=True,
)

ConfigOption = Annotated[
    Path,
    typer.Option("--config", "-c", help="YAML run configuration.", show_default=False),
]

_EXIT_FAILURE = 1
_EXIT_USAGE = 2


@app.command()
def generate(config: ConfigOption) -> None:
    """Generate reference trajectories and write them to the data store."""
    resolved = _resolve(config)
    started = time.perf_counter()
    try:
        directory = build_dataset(resolved, progress=typer.echo)
    except NNPhysicsError as error:
        _fail(str(error))
    typer.echo(f"Generated {directory} in {time.perf_counter() - started:.1f}s.")


@app.command()
def verify(
    config: ConfigOption,
    sample: Annotated[
        int,
        typer.Option(
            "--sample",
            help="Trajectories to re-derive from their seeds. Zero checks hashes only.",
            min=0,
        ),
    ] = 4,
) -> None:
    """Check a dataset against its manifest, by hash and by re-derivation."""
    directory = dataset_dir(_resolve(config))
    try:
        report = verify_dataset(directory, sample=sample)
    except NNPhysicsError as error:
        _fail(str(error))
    typer.echo(
        f"Checked {report.shards_checked} shard(s) and re-derived "
        f"{report.trajectories_checked} trajectory(ies) in {directory}."
    )
    if report.ok:
        typer.echo("Dataset verified.")
        return
    for failure in report.failures:
        typer.echo(failure, err=True)
    raise typer.Exit(code=_EXIT_FAILURE)


@app.command()
def stats(
    config: ConfigOption,
    write: Annotated[
        bool,
        typer.Option("--write/--no-write", help="Write the statistics artefact as well."),
    ] = True,
) -> None:
    """Describe a dataset and fit normalisation statistics to its training split."""
    directory = dataset_dir(_resolve(config))
    try:
        manifest = read_manifest(directory / MANIFEST_NAME)
        normalisation = fit_normalisation(directory, manifest)
        if write:
            write_normalisation(directory / NORMALISATION_NAME, normalisation)
    except NNPhysicsError as error:
        _fail(str(error))

    _describe(manifest, directory)
    typer.echo("Normalisation, fitted to the training split alone:")
    for name in normalisation.names:
        entry = normalisation.stats[name]
        suffix = " (constant, scaled by one)" if entry.degenerate else ""
        typer.echo(f"  {name}: mean {entry.mean:+.6g}, std {entry.std:.6g}{suffix}")
    if write:
        typer.echo(f"Wrote {directory / NORMALISATION_NAME}.")


def _describe(manifest: Manifest, directory: Path) -> None:
    """Print what a manifest says about a dataset."""
    typer.echo(f"Dataset {directory}")
    typer.echo(
        f"System {manifest.system}, seed {manifest.seed}, generated by "
        f"nnphysics {manifest.code_version}."
    )
    typer.echo(
        f"{len(manifest.trajectories)} trajectories of {manifest.spec.n_steps} states, "
        f"stored step {manifest.spec.dt:g}, solver step {manifest.spec.solver_dt:g} "
        f"({manifest.spec.substeps} substep(s))."
    )
    for record in manifest.regimes:
        typer.echo(f"  {record.role.value:>8}  {record.name} x{record.n_trajectories}")
    for split in Split:
        typer.echo(f"  {split.value:>10}: {len(manifest.split(split))} trajectories")
    typer.echo(f"Dataset hash {manifest.dataset_hash}.")


def _resolve(config: Path) -> RunConfig:
    """Load a configuration, reporting failures as a clean exit."""
    try:
        return load_run_config(config, os.environ)
    except NNPhysicsError as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=_EXIT_USAGE) from error


def _fail(message: str) -> NoReturn:
    """Report a failure from the data layer and exit."""
    typer.echo(message, err=True)
    raise typer.Exit(code=_EXIT_FAILURE)
